### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by xqliang** [nameko/nameko#356]
I encounter an exception when start running a service: 

```
$ nameko run --config config.yml service
Traceback (most recent call last):
  File "/home/cc/.virtualenvs/user/bin/nameko", line 11, in <module>
    load_entry_point('nameko==2.4.0', 'console_scripts', 'nameko')()
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/nameko/cli/main.py", line 6, in <module>
    from . import backdoor, run, shell
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/nameko/cli/shell.py", line 13, in <module>
    from nameko.standalone.rpc import ClusterRpcProxy
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/nameko/standalone/rpc.py", line 6, in <module>
    from amqp.exceptions import ConnectionError
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/amqp/__init__.py", line 48, in <module>
    from .basic_message import Message      # noqa
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/amqp/basic_message.py", line 29, in <module>
    from .serialization import GenericContent
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/amqp/serialization.py", line 33, in <module>
    from .exceptions import FrameSyntaxError
  File "/home/cc/.virtualenvs/user/local/lib/python2.7/site-packages/amqp/exceptions.py", line 264, in <module>
    _method_name
TypeError: Struct() argument 1 must be string, not unicode
```

Python: 2.7.3
Nameko: 2.4.0

Because of the `amqp-2.1.0` required by `kombu>=4.0` triggers the [struct.pack fails first time with unicode fmt](https://bugs.python.org/issue19099) bug.

``` python
# amqp-2.1.0 required by kombu>=4.0
262 for _method_id, _method_name in list(METHOD_NAME_MAP.items()):
263     METHOD_NAME_MAP[unpack(u'>I', pack(u'>HH', *_method_id))[0]] = \
264         _method_name
```

``` python
# amqp-2.0.3 required by kombu<4.0
262 for _method_id, _method_name in list(METHOD_NAME_MAP.items()):
263     METHOD_NAME_MAP[unpack(str('>I'), pack(str('>HH'), *_method_id))[0]] = \
264         _method_name
```

We can change the Nameko requirement from `kombu>=3.0.1` to `kombu<4.0,>=3.0.1` to avoid this.

**Comment by mattbennett** [comment]
Nameko doesn't pin `amqp` to a specific version so it should float to whatever is set by kombu, which ought to be compatible. This seems like a packaging problem with kombu's RC.

**Comment by davidszotten** [comment]
kombu 4 is now out and we're not compatible out of the box, so we're pinning it below 4 for now
