### ISSUE TITLE
maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by greole** [nameko/nameko#411]
I am trying to make a request from within a nameko service.

```
import requests

class Service:

    requests.get('https://www.python.org')

    @rpc
    def test(self):
        return "foo"
```
However I am running into following error. What am I missing?

```
Traceback (most recent call last):
  File "/home/go/.local/bin//nameko", line 11, in <module>
    load_entry_point('nameko==2.5.1', 'console_scripts', 'nameko')()
  File "/home/go/.local/lib/python3.7/site-packages/nameko-2.5.1-py3.7.egg/nameko/cli/main.py", line 62, in main
  File "/home/go/.local/lib/python3.7/site-packages/nameko-2.5.1-py3.7.egg/nameko/cli/commands.py", line 85, in main
  File "/home/go/.local/lib/python3.7/site-packages/nameko-2.5.1-py3.7.egg/nameko/cli/run.py", line 178, in main
  File "/home/go/.local/lib/python3.7/site-packages/nameko-2.5.1-py3.7.egg/nameko/cli/run.py", line 45, in import_service
  File "./test.py", line 12, in <module>
    class Service:
  File "./test.py", line 14, in Service
    requests.get('https://www.python.org')
  File "/home/go/.local/lib/python3.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/go/.local/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/go/.local/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/home/go/.local/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/home/go/.local/lib/python3.7/site-packages/requests/packages/urllib3/connection.py", line 311, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/home/go/.local/lib/python3.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 264, in create_urllib3_context
    context.options |= options
  File "/usr/local/lib/python3.7/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.7/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.7/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 319 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by mattbennett** [comment]
Your `requests.get` call is being made at class definition time. Service classes in Nameko used to define a service, and there's quite a lot of magic that happens between a service being defined and it actually running.

What are you trying to achieve here? When did you expect your request to be made?

**Comment by greole** [comment]
I'd like to have a service that connects at start up to some external site to do some data fetching every once in a while.  Then some data processing inside the data handler takes place and the result would be accessible via the rpc call. 


```
import requests

class Service:

    data_handler = Connector()

    @rpc
    def test(self):
        return data_handler.get_current_mean()

```

I though the request would be made on startup of  the service ` nameko run   test`. Should this be implemented via dependency injection? I could not figure it out from the docs.

**Comment by mattbennett** [comment]
Yes, the docs are sparse. Sorry about that. I plan to give them some more attention soon. In the mean time I will try to explain here.

Pretty much every time you want your service to talk to an external entity it should use a dependency provider, because it makes testing easier. In this case, you also need to be able to do something outside of a worker.

Remember that a [worker](http://nameko.readthedocs.io/en/stable/key_concepts.html#workers) only exists for the duration of a method call -- that is, one will be created when you call the RPC method, and it'll be destroyed again afterwards -- and the "dependency" that it sees is whatever the dependency provider returned from its `get_dependency` method.

The dependency provider lives as long as the service is running. You can write one that creates a background thread that fetches your data periodically, so it's available whenever the RPC method fires.

Here's a quick example:

```python
import time
import requests
from nameko.extensions import DependencyProvider
from nameko.rpc import rpc


class Collector(DependencyProvider):

    latest_data = None

    def run(self):
        # fetch latest data every 60 seconds
        while True:
            self.latest_data = requests.get("https://example.com/data")
            time.sleep(60)

    def start(self):
        # ask the container to run a thread for you
        self.container.spawn_managed_thread(self.run)

    def get_dependency(self, worker_ctx):
        # return the data
        return self.latest_data


class Service:
    name = "service"

    data = Collector()

    @rpc
    def test(self):
        # self.data is now a reference to the collector instance's "latest_data" attr
        return get_current_mean(self.data)
```

A better dependency provider may use the "wrapper" pattern ([example here](https://github.com/nameko/nameko-examples/blob/master/products/products/dependencies.py))  and return something with a `get_current_mean` method rather than the raw data (or indeed precalculates the mean), but hopefully you see what I mean.

**Comment by greole** [comment]
It runs now. Thx for your help. The `recursion depth exceeded` error was related to python3.7 and it runs flawlessly with python 3.4.
