### ISSUE TITLE
Does nameko DependencyProvider not support unicode?

### ISSUE THREAD

**Issue by Blackbelly** [nameko/nameko#453]
I use nameko.extensions to connect to MongoDB with mongokit, just like nameko-sqlalchemy. Usage is as follows:
```
from nameko.rpc import rpc
from nameko_mongokit.database import Collection

class ReplyRuleService:
    name = 'replyrule'
    coll = Collection(db_name='test')

    @rpc
    def find(self):
        print(self.coll)
        r = self.coll.find_random()
        print(r)
```

I run it on terminal:
`n.rpc.replyrule.find()`
It could print `self.coll` as `Collection(Database(MongoClient('localhost', 27017), 'test'), 'replyrule’)`, but couldn't print `r`, and raise `nameko.exceptions.RemoteError`:
```
Collection(Database(MongoClient('localhost', 27017), 'test'), 'replyrule’)

error handling worker <WorkerContext [replyrule.find] at 0x1049462e8>: 'ascii' codec can't encode characters in position 60-63: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/apple/Documents/my_projects/venv/lib/python3.6/site-packages/nameko/containers.py", line 384, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./replyrule.py", line 60, in find
    print(r)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 60-63: ordinal not in range(128)


Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/apple/Documents/my_projects/venv/lib/python3.6/site-packages/nameko/rpc.py", line 393, in __call__
    return reply.result()
  File "/Users/apple/Documents/my_projects/venv/lib/python3.6/site-packages/nameko/rpc.py", line 379, in result
    raise deserialize(error)
nameko.exceptions.RemoteError: UnicodeEncodeError 'ascii' codec can't encode characters in position 60-63: ordinal not in range(128)
```

but when I run directly using python command, there is no error:
```
from mongokit import Connection

conn = Connection()
coll = conn.test.replyrule   # collection
print(coll)
r = coll.find_random()
print(r)
```

```
Collection(Database(MongoClient('localhost', 27017), 'test'), 'replyrule’)

{'_id': ObjectId('5955bd5a33339d067494a99e'), 'rule_name': '回复语音', 'create_time': 1498046133, 'reply_mode': 'random_one', 'keyword_list_info': [{'type': 'text', 'match_mode': 'contain', 'content': '获取语音'}], 'reply_list_info': [{'type': 'voice', 'content': 'oTyinC0Lthj9LNdTvvdhp6uRVJ0KbLmVTlBEo2NXa5SE5y7QZ-sTmZK7hPOCOkdy'}]}
```
The field `rule_name` contains unicode characters, but it couldn't be print out with rpc proxy.

**Comment by Ryannnnnnn** [comment]
I think it's irrelevant to nameko, but about your terminal encodings. You can check if `sys.stdout.encoding` is 'utf-8'.

**Comment by Blackbelly** [comment]
@Ryannnnnnn  Thanks. The terminal in Pycharm IDE does not support unicode. I run the service on OS X terminal and it works. 谢谢基佬!
