### ISSUE TITLE
RPC erroneously restarted if connection between worker and broker times out

### ISSUE THREAD

**Issue by frexvahi** [nameko/nameko#477]
On further investigation of #475, I have a better idea what the real problem is:

If the RPC worker runs for too long without yielding to the eventlet event loop, the connection between the worker and broker will time out, causing the broker to send the job to the worker again even though the worker has successfully returned a value.

Here's a simple example:

```
import datetime
import itertools
from nameko.rpc import rpc


class PrimeService:
    name = "prime_service"

    @rpc
    def prime(self, n):
        print("Calculating %dth prime" % (n,))
        print("Calculation started at: ", datetime.datetime.utcnow().isoformat())
        
        primes = []
        for i in itertools.count(2):
            for p in primes:
                if (i % p) == 0:
                    break
            else:
                primes.append(i)
            if len(primes) >= n:
                break
        p = primes[-1]
        print("Calculation completed at: ", datetime.datetime.utcnow().isoformat())
        print("%dth prime is %d" % (n, p))
        return p
```

The nameko shell session looks like this. Note that the second call successfully returns a value
```
$ nameko shell
Broker: b'pyamqp://guest:guest@localhost'
In [1]: %time n.rpc.prime_service.prime(10000)
CPU times: user 20 ms, sys: 8 ms, total: 28 ms
Wall time: 3.11 s
Out[1]: 104729

In [2]: %time n.rpc.prime_service.prime(100000)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 5min 11s
Out[2]: 1299709
```

From the nameko service I see the following. Note that after the failed connection it starts the calculation of the hundred thousandth prime again.
```
$ nameko run primeservice
starting services: prime_service
Connected to amqp://guest:**@127.0.0.1:5672//
Calculating 10000th prime
Calculation started at:  2017-09-25T14:08:42.720720
Calculation completed at:  2017-09-25T14:08:45.784964
10000th prime is 104729
Calculating 100000th prime
Calculation started at:  2017-09-25T14:09:09.161592
Calculation completed at:  2017-09-25T14:14:20.252173
100000th prime is 1299709
Connection to broker lost, trying to re-establish connection...
Traceback (most recent call last):
  File "python3.6/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "python3.6/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "python3.6/site-packages/kombu/connection.py", line 288, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "python3.6/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "python3.6/site-packages/amqp/connection.py", line 303, in drain_events
    chanmap, None, timeout=timeout,
  File "python3.6/site-packages/amqp/connection.py", line 366, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "python3.6/site-packages/amqp/connection.py", line 337, in read_timeout
    return self.method_reader.read_method()
  File "python3.6/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "python3.6/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "python3.6/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/site-packages/amqp/transport.py", line 283, in _read
    raise IOError('Socket closed')
OSError: Socket closed
Connected to amqp://guest:**@127.0.0.1:5672//
Calculating 100000th prime
Calculation started at:  2017-09-25T14:14:20.272356
```

Maybe there's nothing that can be done about this from the nameko level but perhaps it could be documented as a potential pitfall.

**Comment by frexvahi** [comment]
I found a workaround - run the non-yielding function with `eventlet.tpool`

```
import datetime
import itertools
import eventlet.tpool
from nameko.rpc import rpc


class PrimeService:
    name = "prime_service"

    @rpc
    def prime(self, n):
        return eventlet.tpool.execute(self._prime, n)
    
    def _prime(self, n):
        primes = []
        for i in itertools.count(2):
            for p in primes:
                if (i % p) == 0:
                    break
            else:
                primes.append(i)
            if len(primes) >= n:
                break
        p = primes[-1]
        return p
```

**Comment by mattbennett** [comment]
Nice investigation.

You're right that there's nothing that can be done at the Nameko level, but it does deserve calling out in the docs.

This is a limitation of cooperatively yielding co-routines -- if they don't yield, they starve any other threads. This is particularly a problem in Nameko if you're using the AMQP extensions, because the consumer thread needs to send a heartbeat periodically. If the consumer misses two heartbeats the broker assumes the connection is dead and kills it from the other end, and since Nameko's delivery promise is "at least once", the unack'd message will be requeued.

This is the intended behaviour. The workaround you've identified is valid, as would be explicitly yielding somewhere in your prime calculation.

Eventlet will automatically yield for you if your thread blocks for I/O. If your workload is entirely CPU-based it's good practice to yield periodically to avoid starving other threads and to allow more balanced scheduling. If it's not possible to yield (e.g. if the work happens inside a c-extension) then delegating to a normal thread via the tpool is the way to do it.

**Comment by geoffjukes** [comment]
Wanted to say thank @frexvahi for your investigation and fix here. This helped be figure out an issue I was having,which I thought was network related - but was actually a (very) long running subprocess call blocking.

In my case, I was able to switch to the `greened` subprocess.

**Comment by vashchukmaksim** [comment]
Have the same problem, but the workaround does not help. Have two services with RPC and each of them throws that errors while no requests are made. It can happen one time during 10 minutes, or 30 minutes or 1 hour. All works fine (before and after reconnect I suppose) but logs are messy with those errors.

nameko==2.12.0
kombu==4.6.5
