### ISSUE TITLE
one of our rpc call fails and success in a sequence

### ISSUE THREAD

**Issue by gitricko** [nameko/nameko#548]
Hi,

Just a trying to crowdsource a possible solution or why a particular error occur. We have a few services that implement a rpc method called heartbeat. Only one particular service has this error (see below) it success and fail and repeat in this pattern. 

We check our coding and there is nothing specially between this service with others. Our fix was to create rabbitmq instance again (in cloudfoundry backing service)

```
>>> n.rpc.etc.heartbeat()
True
>>> n.rpc.etc.heartbeat()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vcap/deps/0/conda/envs/dep_env/lib/python3.6/site-packages/nameko/rpc.py", line 374, in __call__
    return reply.result()
  File "/home/vcap/deps/0/conda/envs/dep_env/lib/python3.6/site-packages/nameko/rpc.py", line 332, in result
    raise deserialize(error)
nameko.exceptions.MethodNotFound: heartbeat
>>> n.rpc.etc.heartbeat()
True
>>> n.rpc.etc.heartbeat()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vcap/deps/0/conda/envs/dep_env/lib/python3.6/site-packages/nameko/rpc.py", line 374, in __call__
    return reply.result()
  File "/home/vcap/deps/0/conda/envs/dep_env/lib/python3.6/site-packages/nameko/rpc.py", line 332, in result
    raise deserialize(error)
nameko.exceptions.MethodNotFound: heartbeat


```

**Comment by davidszotten** [comment]
hi,

it looks like you might have two service instances with the same name running, one with that method and one without it. 

for future reference, [the forum](https://groups.google.com/forum/#!forum/nameko-dev) is usually a better place for questions like this.

**Comment by gitricko** [comment]
Thanks for the feedback.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/one-of-our-rpc-call-fails-and-success-in-a-sequence/289
