### ISSUE TITLE
RuntimeError: no suitable implementation for this system

### ISSUE THREAD

**Issue by xiongqiangcs** [nameko/nameko#550]
After `nameko run helloworld`,  appear

```
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:13> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:14> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:16> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:17> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:8> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:9> ignored
starting services: greeting_service
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:7> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:10> ignored
Traceback (most recent call last):
  File "/home/XXXXX/anaconda2/bin/nameko", line 11, in <module>
    sys.exit(main())
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/cli/main.py", line 104, in main
    args.main(args)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/cli/run.py", line 184, in main
    run(services, config, backdoor_port=args.backdoor_port)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/cli/run.py", line 131, in run
    service_runner.start()
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/runners.py", line 66, in start
    SpawningProxy(self.containers).start()
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/nameko/utils/__init__.py", line 186, in spawning_method
    return list(pool.imap(call, self._items))
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/greenpool.py", line 175, in imap
    return self.starmap(function, six.moves.zip(*iterables))
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/greenpool.py", line 160, in starmap
    eventlet.spawn_n(self._do_map, function, iterable, gi)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/greenthread.py", line 66, in spawn_n
    return _spawn_n(0, func, args, kwargs)[1]
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/greenthread.py", line 156, in _spawn_n
    hub = hubs.get_hub()
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

**Comment by mattbennett** [comment]
Please see #533 for an explanation of this.
