### ISSUE TITLE
An error occurred while running too many services  in windows

### ISSUE THREAD

**Issue by huyidao625** [nameko/nameko#551]
**code like this**

```python
class Test:
    name = "test"
    @rpc
    def do(self,name):
        print (name)
        return "test, {n}!".format(n=name)

if __name__ == '__main__':
    service_runner = ServiceRunner(config)
    for i in range(1000):
        Test.name += '_'+str(i)
        service_runner.add_service(Test)
        Test.name ='test'
    service_runner.start()     
    service_runner.wait()
```

**error**

```python
Traceback (most recent call last):
  File "C:\Users\hufei\eclipse-workspace2\Test\containers2.py", line 34, in <module>
    service_runner.start()     
  File "C:\Python36\lib\site-packages\nameko\runners.py", line 66, in start
    SpawningProxy(self.containers).start()
  File "C:\Python36\lib\site-packages\nameko\utils\__init__.py", line 186, in spawning_method
    return list(pool.imap(call, self._items))
  File "C:\Python36\lib\site-packages\eventlet\greenpool.py", line 244, in next
    val = self.waiters.get().wait()
  File "C:\Python36\lib\site-packages\eventlet\greenthread.py", line 179, in wait
    return self._exit_event.wait()
  File "C:\Python36\lib\site-packages\eventlet\event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "C:\Python36\lib\site-packages\eventlet\hubs\hub.py", line 295, in switch
    return self.greenlet.switch()
  File "C:\Python36\lib\site-packages\eventlet\hubs\hub.py", line 349, in run
    self.wait(0)
  File "C:\Python36\lib\site-packages\eventlet\hubs\selects.py", line 38, in wait
    r, w, er = select.select(readers.keys(), writers.keys(), all_fds, seconds)
ValueError: too many file descriptors in select()
```

**version**

    os ==  Win7 _x86_64
    nameko == 2.9.0
    rabbitmq==3.7.4

**Comment by mattbennett** [comment]
This is what is sounds like -- your process ran out of file descriptors. The maximum number of file descriptors per process is controlled by the operating system.

Running 1000 services in a single process doesn't seem like a good idea. You'll get better performance splitting your workload across multiple processes because a Python process cannot use more than one CPU core. In fact, my recommendation is to use a process per Nameko service for most workloads.
