### ISSUE TITLE
Nameko not working with urllib

### ISSUE THREAD

**Issue by lorenzoferrante** [nameko/nameko#590]
Hi everyone, my problem is that Nameko is not working properly with urllib for me. 
I'm using python 3.6 on a Windows 10 machine, and I tried to make it work with both Ubuntu on WSL and the Windows shell.
Here's my code:

```python
from nameko.web.handlers import http

class HttpService:
    name = 'http_service'

    @http('GET', '/get/download')
    def get(self, request):
        link, num = get_image('cats')
        return json.dumps({'value': link})

    @http('POST', '/post')
    def post(self, request):
        return u"received: {}\n".format(request.get_data(as_text=True))
```

The get_image() function is defined like that:

```python
import json
from pathlib import Path
from urllib.request import urlopen, Request

def get_image(query, page=1):
    client_id = '...'
    headers = {'Authorization': 'Client-ID {}'.format(client_id)}

    url = 'https://api.imgur.com/3/gallery/search/{}?q={}'.format(page, query)

    req = Request(url, headers=headers, method='GET')

    with urlopen(req) as resp:
        data = json.loads(resp.read().decode('utf8'))

    links = [item['link'] for item in data['data'] if 'type' in item and item['type'] in types]
    return links, len(links)
```

Here is my config.yaml:

```python
# config.yaml
WEB_SERVER_ADDRESS: '0.0.0.0:8080'
```

Here is the error I am getting:

```shell
starting services: http_service
error handling worker <WorkerContext [http_service.get] at 0x7fd745d5f780>:
Traceback (most recent call last):
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/inet.py", line 86, in af_for_address
    dns.ipv4.inet_aton(text)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/ipv4.py", line 48, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/inet.py", line 90, in af_for_address
    dns.ipv6.inet_aton(text)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/ipv6.py", line 153, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/nameko/containers.py", line 391, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./micro.py", line 14, in get
    link, num = get_image('cats')
  File "./download.py", line 51, in get_image
    with urlopen(req) as resp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/green/socket.py", line 44, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 425, in resolve
    use_network=use_network)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 380, in query
    return end()
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 359, in end
    raise result[1]
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/resolver.py", line 962, in query
    source_port=source_port)
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 743, in udp
    if dns.inet.af_for_address(from_address[0]) == dns.inet.AF_INET6:
  File "/mnt/c/Users/Lorenzo/PycharmProjects/Prova/env/local/lib/python3.6/site-packages/dns/inet.py", line 93, in af_for_address
    raise ValueError
ValueError
```

What can I do to solve this issue?
Thanks in advice.

**Comment by mattbennett** [comment]
This seems like a bug in eventlet's `greendns` module. Which version of eventlet do you have installed?

**Comment by lorenzoferrante** [comment]
I have version 0.24.1 both on Windows and Ubuntu on WSL.

**Comment by mattbennett** [comment]
There have been a bunch of changes to `greendns` in the last handful of releases. I would try rolling back through the versions and see if there is one which fixes it. If you can demonstrate that it's an eventlet regression I'm sure the folks over at https://github.com/eventlet/eventlet would appreciate a bug report.

**Comment by lorenzoferrante** [comment]
Ok perfect. I’ll try what you suggested. Thank you.
