### ISSUE TITLE
ImportError: No module named 'urllib2' in python3

### ISSUE THREAD

**Issue by myazid** [nameko/nameko#599]
**Describe the bug**
The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error.

**To Reproduce**
Run sample http.py in document.

**Expected behavior**
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/http.py", line 27, in <module>
    from urllib.request import parse_http_list as _parse_list_header
  File "/usr/lib/python3.5/urllib/request.py", line 88, in <module>
    import http.client
ImportError: No module named 'http.client'; 'http' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nameko", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/nameko/cli/main.py", line 107, in main
    args.main(args)
  File "/usr/local/lib/python3.5/dist-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/nameko/cli/run.py", line 181, in main
    import_service(path)
  File "/usr/local/lib/python3.5/dist-packages/nameko/cli/run.py", line 46, in import_service
    __import__(module_name)
  File "./http.py", line 4, in <module>
    from nameko.web.handlers import http
  File "/usr/local/lib/python3.5/dist-packages/nameko/web/handlers.py", line 6, in <module>
    from werkzeug.routing import Rule
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wrappers.py", line 27, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/http.py", line 30, in <module>
    from urllib2 import parse_http_list as _parse_list_header, \
ImportError: No module named 'urllib2'

**Environment (please complete the following information):**
 - Nameko version: 2.11
 - Python version: 3.52
 - OS: Ubuntu 16:04

**Additional context**
None

**Comment by mattbennett** [comment]
This is happening because the local `http` module is shadowing the `http` package in the standard library. 

```
ImportError: No module named 'http.client'; 'http' is not a package
```

The "another exception occurred" message is a bit misleading. That's an exception thrown while werkzeug is discovering that `urllib2` is not available, and is correct behaviour.

I'll change our example so it suggests using a different module name. Thanks for reporting!
