### ISSUE TITLE
`RuntimeError: invalid RE code` error message when loading nameko

### ISSUE THREAD

**Issue by amnonkhen** [nameko/nameko#607]
**Describe the bug**
`RuntimeError: invalid RE code` error message when loading nameko

stack trace:

```
Traceback (most recent call last):
  File "c:\users\ak81894\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ak81894\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ak81894\AppData\Local\Continuum\anaconda3\Scripts\nameko.exe\__main__.py", line 5, in <module>
  File "c:\users\ak81894\appdata\local\continuum\anaconda3\lib\site-packages\nameko\cli\main.py", line 48, in <module>
    """, regex.VERBOSE
  File "c:\users\ak81894\appdata\local\continuum\anaconda3\lib\site-packages\regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)
  File "c:\users\ak81894\appdata\local\continuum\anaconda3\lib\site-packages\regex.py", line 613, in _compile
    req_offset, req_chars, req_flags, info.group_count)
RuntimeError: invalid RE code
```

**To Reproduce**
run `nameko` commandline tool

**Expected behavior**
nameko should load properly

**Environment (please complete the following information):**
 - Nameko version: 2.11.0
 - Python version: Python 3.6.4 :: Anaconda, Inc.
 - OS: Windows 7

**Additional context**
I tried running the "hello world" example.

**Comment by amnonkhen** [comment]
a workaround for this issue is to force nameko to parse the environment variable regular expression using `re` package rather than `regex` by editing `main.py`

**Comment by kooba** [comment]
Just tried `hello world` example from https://docs.nameko.io/en/stable/#nameko and had no issue. I'm on macOs though. Use of `regex` is [optional](https://github.com/nameko/nameko/blob/master/nameko/cli/main.py#L16) and that dependency is not installed with Nameko by default and `re` should be used. 
Unfortunately none of the developers working on Nameko use Windows OS so there might be some incompatibility.

**Comment by amnonkhen** [comment]
Thanks. 
I uninstalled regex and it did the trick.

**Comment by mattbennett** [comment]
There must be some incompatibility in the pattern used in the nameko CLI and the regex library installed by Anaconda.

Which version of the `regex` module did you have installed?

**Comment by amnonkhen** [comment]
The stacktrace confirms that the compilation of the regexp pattern is what causes the RuntimeError to be throw.
I tried it with `regex` 2018 and latest 2019. Both failed.

**Comment by mattbennett** [comment]
It's tested against `2018.2.21`, so that version at least should work. Would be interesting to see which subsequent release breaks it, and whether there are any notes in the changelog. I would hope that there is a workaround.

I think it's preferable for us to support later versions even if that means dropping support for the older ones. Clearly we're failing to do so at the moment.
