### ISSUE TITLE
Error with default settings in virtualenv

### ISSUE THREAD

**Issue by h8hawk** [nameko/nameko#641]
I cannot run nameko with rabbitmq , here is the log for running first [example](http://docs.nameko.io/en/stable/index.html)

$nameko run helloworld
Traceback (most recent call last):
File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/bin/nameko", line 10, in
sys.exit(main())

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/cli/main.py", line 155, in main
args.main(args)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/cli/commands.py", line 105, in main
main(args)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/cli/run.py", line 175, in main
run(services, backdoor_port=args.backdoor_port)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/cli/run.py", line 118, in run
service_runner.add_service(service_cls)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/runners.py", line 50, in add_service
container = self.container_cls(cls)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/containers.py", line 149, in init
bound = entrypoint.bind(self.interface, method_name)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/extensions.py", line 284, in bind
instance = super(Entrypoint, self).bind(container)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/extensions.py", line 97, in bind
setattr(instance, name, ext.bind(container))

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/extensions.py", line 126, in bind
instance = super(SharedExtension, self).bind(container)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/extensions.py", line 96, in bind
for name, ext in inspect.getmembers(self, is_extension):

File "/usr/lib/python3.7/inspect.py", line 341, in getmembers
value = getattr(object, key)

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/site-packages/nameko/rpc.py", line 66, in amqp_uri
return config[AMQP_URI_CONFIG_KEY]

File "/home/howard/.local/share/virtualenvs/shipupline-5EExyWmr/lib/python3.7/collections/init.py", line 1025, in getitem
raise KeyError(key)
KeyError: 'AMQP_URI'

rabbitmq status:
`$sudo rabbitmqctl status
Status of node rabbit@howard ...
[{pid,784},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.7.15"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.15"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.15"},
      {rabbit,"RabbitMQ","3.7.15"},
      {cowboy,"Small, fast, modern HTTP server.","2.6.1"},
      {amqp_client,"RabbitMQ AMQP Client","3.7.15"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.7.15"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.7.1"},
      {ssl,"Erlang/OTP SSL application","9.3.3"},
      {public_key,"Public key infrastructure","1.6.7"},
      {asn1,"The Erlang ASN1 compiler version 5.0.9","5.0.9"},
      {observer_cli,"Visualize Erlang Nodes On The Command Line","1.5.0"},
      {sysmon_handler,"Rate-limiting system_monitor event handler","1.1.0"},
      {os_mon,"CPO  CXC 138 46","2.5"},
      {recon,"Diagnostic tools for production use","2.5.0"},
      {mnesia,"MNESIA  CXC 138 12","4.16"},
      {xmerl,"XML parser","1.3.21"},
      {cowlib,"Support library for manipulating Web protocols.","2.7.0"},
      {crypto,"CRYPTO","4.5.1"},
      {jsx,"a streaming, evented json parsing toolkit","2.9.0"},
      {inets,"INETS  CXC 138 49","7.0.8"},
      {lager,"Erlang logging framework","3.6.10"},
      {goldrush,"Erlang event stream processor","0.1.9"},
      {compiler,"ERTS  CXC 138 10","7.4.2"},
      {syntax_tools,"Syntax tools","2.2"},
      {sasl,"SASL  CXC 138 11","3.4"},
      {stdlib,"ERTS  CXC 138 10","3.9.2"},
      {kernel,"ERTS  CXC 138 10","6.4.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64]\n"},
 {memory,
     [{connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,2732},
      {queue_procs,0},
      {queue_slave_procs,0},
      {plugins,1042548},
      {other_proc,22427164},
      {metrics,206628},
      {mgmt_db,171864},
      {mnesia,76056},
      {other_ets,2788168},
      {binary,117320},
      {msg_index,29584},
      {code,27361269},
      {atom,1221849},
      {other_system,12167282},
      {allocated_unused,8536272},
      {reserved_unallocated,3629056},
      {strategy,rss},
      {total,[{erlang,67612464},{rss,79777792},{allocated,76148736}]}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"},{http,15672,"::"}]},
 {vm_memory_calculation_strategy,rss},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,3298032025},
 {disk_free_limit,50000000},
 {disk_free,67586584576},
 {file_descriptors,
     [{total_limit,32668},
      {total_used,2},
      {sockets_limit,29399},
      {sockets_used,0}]},
 {processes,[{limit,1048576},{used,390}]},
 {run_queue,1},
 {uptime,1432},
 {kernel,{net_ticktime,60}}]`

It has something to do with pipenv(or virtualenv). code above run fine without pipenv environment.

**Comment by iky** [comment]
Hi @h8hawk , thanks for opening this.

It looks like you are running *pre-release* of Nameko and not setting the `AMQP_URI` needed for connection to rabbit. In the pre-release the defualt AQP URL is missing and this needs to be fixed.

With the latest stable release of Nameko the documentation example works smoothly.

We need to add a default URI for Nameko 3 so if no AMQP URI is provided, the service would connect to localhost with a standard default guest user.

In the meantime, you can provide a config with `AMQP_URI` defined or you can define it in command line:
```shell
$ nameko run helloworld --define AMQP_URI=pyamqp://guest:guest@localhost/
starting services: greeting_service
Connected to amqp://guest:guest@127.0.0.1:5672//
```

Installing stable release is also an option .)

I'll fix the pre-release ASAP.

**Comment by iky** [comment]
@h8hawk the pre-release fix is now released https://github.com/nameko/nameko/releases/tag/v3.0.0-rc7
