### ISSUE TITLE
Nameko can not work with pathlib

### ISSUE THREAD

**Issue by ScienceYuan** [nameko/nameko#642]
**Describe the bug**
nameko worker process raise an exception when calling `Path('anything').open()`. reference to [this issue](https://github.com/eventlet/eventlet/issues/534), that should caused by a bug of eventlet.

**To Reproduce**
`server.py`
```python
from pathlib import Path
from nameko.rpc import rpc


class Test:
    name = 'test'

    @rpc
    def test(self):
        Path('anything').open()
```
`client.py`
```python
from nameko.standalone.rpc import ClusterRpcProxy

with ClusterRpcProxy({'AMQP_URI': 'pyamqp://guest:guest@localhost'}) as cluster_rpc:
    cluster_rpc.test.test()
```
run command line `nameko run server` and `python client.py`.
**Expected behavior**
client crushed and server raised a exception. exception on my machine:
```
Traceback (most recent call last):
  File "/home/***/.local/share/virtualenvs/judger-uPeNMyNf/lib/python3.7/site-packages/nameko/containers.py", line 392, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./server.py", line 10, in test
    Path('anything').open()
  File "/usr/lib64/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib64/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/***/.local/share/virtualenvs/judger-uPeNMyNf/lib/python3.7/site-packages/eventlet/green/os.py", line 107, in open
    fd = __original_open__(file, flags, mode, dir_fd=dir_fd)
TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor

```

**Environment (please complete the following information):**
 - Nameko version: 2.12.0
 - Python version: 3.7.3
 - OS: Manjaro/Linux

**Comment by daviskirk** [comment]
As a simple workaround, in python >= 3.6 you should be able to use the normal builtin `open` function on pathlib objects.  This seems to work fine and should have the exact same result (but without the crash):

```python
import pathlib 

class Test:
    name = 'test'

    @rpc
    def test(self):
        open(Path('anything'))

```

**Comment by Mendes11** [comment]
I'm having the same issue, my problem is that I'm trying to load a service that has scikit-learn lib imported. Is there any workaround?

The traceback:

```
Traceback (most recent call last):
  File "/home/mendes/.virtualenvs/brain_predict/bin/nameko", line 10, in <module>
    sys.exit(main())
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/main.py", line 112, in main
    args.main(args)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/run.py", line 181, in main
    import_service(path)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/run.py", line 46, in import_service
    __import__(module_name)
  File "./service/service.py", line 6, in <module>
    from service.model_trainer import start_model_training
  File "./service/model_trainer.py", line 6, in <module>
    from predictors.predict import models_evaluation
  File "./predictors/predict.py", line 4, in <module>
    from predictors.ar import AutoregressionModel
  File "./predictors/ar.py", line 3, in <module>
    from sklearn.metrics import mean_squared_error
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 35, in <module>
    from ..preprocessing import label_binarize
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/utils/testing.py", line 718, in <module>
    import pytest
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pytest.py", line 8, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 13, in <module>
    from _pytest.assertion import rewrite
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/util.py", line 11, in <module>
    import _pytest._code
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 7, in <module>
    from .code import Code  # noqa
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
    __version__ = version(__name__)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
    return distribution(package).version
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 226, in version
    return self.metadata['Version']
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 214, in metadata
    self.read_text('METADATA')
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 398, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/eventlet/green/os.py", line 107, in open
    fd = __original_open__(file, flags, mode, dir_fd=dir_fd)
TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor
```

**Comment by davidszotten** [comment]
eventlet 0.25.1 is now available with a fix for the pathlib issue
