### ISSUE TITLE
Nameko can't patch sklearn

### ISSUE THREAD

**Issue by Mendes11** [nameko/nameko#650]
I'm having the same issue, my problem is that I'm trying to load a service that has scikit-learn lib imported. Is there any workaround?

The traceback:

```
Traceback (most recent call last):
  File "/home/mendes/.virtualenvs/brain_predict/bin/nameko", line 10, in <module>
    sys.exit(main())
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/main.py", line 112, in main
    args.main(args)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/run.py", line 181, in main
    import_service(path)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/nameko/cli/run.py", line 46, in import_service
    __import__(module_name)
  File "./service/service.py", line 6, in <module>
    from service.model_trainer import start_model_training
  File "./service/model_trainer.py", line 6, in <module>
    from predictors.predict import models_evaluation
  File "./predictors/predict.py", line 4, in <module>
    from predictors.ar import AutoregressionModel
  File "./predictors/ar.py", line 3, in <module>
    from sklearn.metrics import mean_squared_error
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 35, in <module>
    from ..preprocessing import label_binarize
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/sklearn/utils/testing.py", line 718, in <module>
    import pytest
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pytest.py", line 8, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 13, in <module>
    from _pytest.assertion import rewrite
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/assertion/util.py", line 11, in <module>
    import _pytest._code
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 7, in <module>
    from .code import Code  # noqa
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
    __version__ = version(__name__)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
    return distribution(package).version
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 226, in version
    return self.metadata['Version']
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 214, in metadata
    self.read_text('METADATA')
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 398, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/mendes/.virtualenvs/brain_predict/lib/python3.7/site-packages/eventlet/green/os.py", line 107, in open
    fd = __original_open__(file, flags, mode, dir_fd=dir_fd)
TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor
```

**Comment by mattbennett** [comment]
This is a bug in eventlet and unfortunately there's no easy fix if the [workaround](https://github.com/nameko/nameko/issues/642#issuecomment-506950873) in #642 isn't possible for you.

The good news is that @daviskirk is working on removing the dependency on eventlet in #647.

**Comment by Mendes11** [comment]
Yeah, I imagined... Hopefullly we have Docker and pyenv to be able to install any python version we want :)

That's how I managed this.

> The good news is that @daviskirk is working on removing the dependency on eventlet in #647.

Nice :)

**Comment by davidszotten** [comment]
eventlet 0.25.1 is now available with a fix for the pathlib issue
