### ISSUE TITLE
I always get an error when I use the nameko shell command

### ISSUE THREAD

**Issue by kuoiea** [nameko/nameko#653]
(venv) [kuoiea@test ~]$ nameko shell
Traceback (most recent call last):
  File "/home/kuoiea/adviser/venv/bin/nameko", line 11, in <module>
    sys.exit(main())
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/cli/main.py", line 112, in main
    args.main(args)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/cli/commands.py", line 143, in main
    main(args)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/cli/shell.py", line 98, in main
    ctx['n'] = make_nameko_helper(config)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/cli/shell.py", line 73, in make_nameko_helper
    module.rpc = proxy.start()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 228, in start
    self._reply_listener.setup()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/rpc.py", line 260, in setup
    self.queue_consumer.register_provider(self)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 123, in register_provider
    self._setup_consumer()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 102, in _setup_consumer
    channel = self.connection.channel()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/kombu/connection.py", line 280, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/amqp/connection.py", line 313, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/amqp/connection.py", line 505, in blocking_read
    frame = self.transport.read_frame()
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/amqp/transport.py", line 252, in read_frame
    frame_header = read(7, True)
  File "/home/kuoiea/adviser/venv/lib/python3.6/site-packages/amqp/transport.py", line 436, in _read
    s = recv(n - len(rbuf))
socket.timeout: timed out

-----------------------------------------------------------------------------------------------------------------------------

(venv) [kuoiea@test ~]$ pip list
Package            Version  
------------------ ---------
amqp               2.5.0    
atomicwrites       1.3.0    
attrs              19.1.0   
certifi            2019.6.16
chardet            3.0.4    
dnspython          1.16.0   
eventlet           0.25.0   
greenlet           0.4.15   
idna               2.8      
importlib-metadata 0.19     
kombu              4.6.3    
mock               3.0.5    
monotonic          1.5      
more-itertools     7.2.0    
nameko             2.12.0   
packaging          19.1     
path.py            12.0.1   
pika               0.13.0   
pip                19.2.2   
pluggy             0.12.0   
py                 1.8.0    
PyAMQP             0.0.8.1  
pyparsing          2.4.2    
pytest             5.0.1    
PyYAML             5.1.2    
requests           2.22.0   
setuptools         39.0.1   
six                1.12.0   
urllib3            1.25.3   
vine               1.3.0    
wcwidth            0.1.7    
Werkzeug           0.15.5   
wrapt              1.11.2   
zipp               0.5.2

------------------------------------------------------------------------------------------------------------------

**Comment by vlcinsky** [comment]
@kuoiea you are reporting the issue against nameko version 2.12.0. Consider testing the issue against version or branch v3.0.0-rc

To me it seems, the stacktrace shows problems to connect to amqp broker. You are probably missing amqp broker configuration or the amqp server is currently not running.
