### ISSUE TITLE
Default value for `--amqp-ssl-option` (pytest) breaks compatibility with pytest-xdist

### ISSUE THREAD

**Issue by signalpillar** [nameko/nameko#657]
**Describe the bug**
Not able to run the tests in parallel using pytest-xdist plugin.

pytest option for SSL `--amqp-ssl-option` fail serialisation of the pytest options for worker.
The option has the the defaults that contain value of type enum in it.

```
 {'AMQP_SSL_OPTIONS': [('ca_certs', 'certs/cacert.pem'),
                       ('certfile', 'certs/clientcert.pem'),
                       ('keyfile', 'certs/clientkey.pem'),
                       ('cert_reqs', <VerifyMode.CERT_REQUIRED: 2>)],
```

`pytest` tries to serialise those and fails.

<details><summary>Full stack trace</summary>
<p>

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1400, in _save
INTERNALERROR>     dispatch = self._dispatch[tp]
INTERNALERROR> KeyError: <enum 'VerifyMode'>
INTERNALERROR>
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/_pytest/main.py", line 176, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/xdist/dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/xdist/workermanage.py", line 68, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/xdist/workermanage.py", line 77, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/xdist/workermanage.py", line 253, in setup
INTERNALERROR>     self.channel.send((self.workerinput, args, option_dict, change_sys_path))
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 729, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1371, in dumps_internal
INTERNALERROR>     return _Serializer().save(obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1389, in save
INTERNALERROR>     self._save(obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1494, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1490, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1484, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1480, in save_list
INTERNALERROR>     self._write_setitem(i, item)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1484, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1494, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File ".tox/test_service/lib/python3.6/site-packages/execnet/gateway_base.py", line 1405, in _save
INTERNALERROR>     raise DumpError("can't serialize {}".format(tp))
INTERNALERROR> execnet.gateway_base.DumpError: can't serialize <enum 'VerifyMode'>
```

</p>
</details>

**To Reproduce**
`pytest --tx '3*popen//execmodel=eventlet' --dist load -v tests`

**Expected behavior**
The tests are parallelised regardless wether option is used or not.

**Environment (please complete the following information):**
 - Nameko version: 2.12.0
 - Python version: 3.6.4
 - OS: macOS 10.14

**Additional context**
Unfortunately `append` action of the option doesn't allow to redefine the defaults, I didn't find how to do it.

What do you think about the following possible fix?

`nameko/testing/pytest.py`

1. Change the default for `cert_reqs` to be a name of the member in `ssl.VerifyMode` so we can easily verify and resolve it.

```python
    parser.addoption(
        '--amqp-ssl-option',
        type=parse_config_option,
        action='append',
        dest='AMQP_SSL_OPTIONS',
        metavar='KEY=VALUE',
        default=[
            ('ca_certs', 'certs/cacert.pem'),
            ('certfile', 'certs/clientcert.pem'),
            ('keyfile', 'certs/clientkey.pem'),

---->   ('cert_reqs', 'CERT_REQUIRED')

        ],
        help=(
            'SSL connection options for passing to ssl.wrap_socket.'
            'Multiple options may be given. Values are parsed as YAML, '
            'hence the following example is valid: \n'
            '--amqp-ssl-option certfile=clientcert.pem '
            '--amqp-ssl-option ssl_version=!!python/name:ssl.PROTOCOL_TLSv1_2'
        )
    )
```
2. The option is used in one fixture only `rabbit_ssl_config` so I suggest to handle the value there.

```python
    import ssl
    from six.moves.urllib.parse import urlparse  # pylint: disable=E0401

    ssl_options = request.config.getoption('AMQP_SSL_OPTIONS')
    ssl_options = {key: value for key, value in ssl_options} or True

    # Extensive comment goes here WHY we do this
    cert_reqs = ssl_options.get('cert_reqs')
    if isinstance(cert_reqs, str):
        ssl_options['cert_reqs'] = ssl.VerifyMode[cert_reqs]
    ...
```

I can make the PR if you think the approach is OK.

3. Other thing, I am an expert in these options but I see that `kombu/connection.py:Connection._init_params` sets `ssl_cert_reqs` if not specified not `cert_reqs` as we do in `pytest` plugin. Do we use it correctly?

**Comment by mattbennett** [comment]
Thanks for reporting this. I think your proposed fix is fine and would welcome a PR.

Re: `ssl_cert_reqs` vs `cert_reqs`. The [docstring](https://github.com/celery/kombu/blob/574641e01fb284e3f5d5833da5fefd0e12d8b23a/kombu/connection.py#L73) certainly suggests using `cert_reqs`. The only reference I see to `ssl_cert_reqs` [is here](https://github.com/celery/kombu/blob/574641e01fb284e3f5d5833da5fefd0e12d8b23a/kombu/connection.py#L250), which relates to redis connections only. Are you referring to somewhere else?
