### ISSUE TITLE
Set exitcode when service is not found

### ISSUE THREAD

**Issue by litnimax** [nameko/nameko#666]
In the following code when bad app is specified we get an error and non-zero status code.
But when app is ok but service is wrong we do not get an exception and status code is 0.
So I cannot trace when wrong service is called.
Please have a look: 
```
max@MacBook-Pro-Max tmp % nameko run no_service.no_app --config=config.yml
Traceback (most recent call last):
  File "/Users/max/Library/Python/3.7/bin//nameko", line 10, in <module>
    sys.exit(main())
  File "/Users/max/Library/Python/3.7/lib/python/site-packages/nameko/cli/main.py", line 112, in main
    args.main(args)
  File "/Users/max/Library/Python/3.7/lib/python/site-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/Users/max/Library/Python/3.7/lib/python/site-packages/nameko/cli/run.py", line 181, in main
    import_service(path)
  File "/Users/max/Library/Python/3.7/lib/python/site-packages/nameko/cli/run.py", line 46, in import_service
    __import__(module_name)
ModuleNotFoundError: No module named 'no_service'

max@MacBook-Pro-Max tmp % echo $?
1
```

Now with wrong sub-service:
```
max@MacBook-Pro-Max tmp % nameko run test_app.no_app --config=config.yml
Error: No module named 'test_app.no_app'
max@MacBook-Pro-Max tmp % echo $?
0
```

**Comment by bow** [comment]
I can confirm this is also the case in my dev installation of Nameko 2.12.0. This seems to be caused by [this line](https://github.com/nameko/nameko/blob/master/nameko/cli/main.py#L121) only printing the error message but not exiting the process afterwards with a nonzero exit code.

This seems to have been fixed in `3.0.0`, as the underlying CLI parsing module has been updated. Still, would it be useful to patch `2.12.0` to correctly return an error exit code here?
