### ISSUE TITLE
Unable to get result for async rpc calls

### ISSUE THREAD

**Issue by sidharthramesh** [nameko/nameko#672]
**Describe the bug**
When `r.result()` of an async method is called, I get a runtime error. I am using docker and docker-compose. I may be doing something obviously wrong, but I can't figure out what.
```
starting services: regular_checker, worker
Connected to amqp://guest:**@rabbitmq:5672//
error handling worker <WorkerContext [regular_checker.ping] at 0x7fe94214d430>: This consumer has been stopped, and can no longer be used
Traceback (most recent call last):
...
...
  File "./app.py", line 18, in ping
    results = [r.result() for r in results]
  File "./app.py", line 18, in <listcomp>
    results = [r.result() for r in results]
  File "/usr/local/lib/python3.8/site-packages/nameko/rpc.py", line 326, in result
    self.resp_body = self.reply_event.wait()
  File "/usr/local/lib/python3.8/site-packages/nameko/standalone/rpc.py", line 52, in wait
    raise RuntimeError(
RuntimeError: This consumer has been stopped, and can no longer be used
```
**To Reproduce**
I am using docker and docker-compose. To reproduce the error:

*app.py*
```python
from nameko.timer import timer
from nameko.standalone.rpc import ClusterRpcProxy
from nameko.rpc import rpc
from nameko.runners import ServiceRunner
import logging

class RegularChecker:
    name = "regular_checker"
    @timer(interval=1)
    def ping(self):
        results = []
        for i in range(10):
            with ClusterRpcProxy(config={"AMQP_URI":"pyamqp://guest:guest@rabbitmq"}) as cluster:
                r = cluster.worker.sleep.call_async(i)
                results.append(r)
        
        # Wait for all results to finish
        results = [r.result() for r in results]
        logging.info(results)

class Worker:
    name = "worker"
    @rpc
    def sleep(self, number):
        import time
        time.sleep(0.5)
        return number
```

*Dockerfile*
```dockerfile
FROM python:3.8.1
RUN pip install nameko
WORKDIR /src/
```

*docker-compose.yml*
```yaml
version: "3.7"

services: 
    rabbitmq:
            image: rabbitmq:3.7-alpine
    app:
        build: .
        volumes: 
            - ./:/src/
        depends_on: 
            - rabbitmq
        command: nameko run app --broker rabbitmq
```

command:
```
docker-compose run app
```
**Expected behavior**
The result gets returned without an error

**Environment (please complete the following information):**
 - Nameko version: 2.12.0
 - Python version: 3.8.1
 - OS: Manjaro Linux 19.0

**Comment by sidharthramesh** [comment]
Ok. I just realised that using `RpcProxy` instead of `ClusterRpcProxy` works.

So my *app.py* should have been:
```python
from nameko.timer import timer
from nameko.standalone.rpc import ClusterRpcProxy
from nameko.rpc import rpc, RpcProxy
from nameko.runners import ServiceRunner
import logging

class RegularChecker:
    name = "regular_checker"
    worker = RpcProxy("worker") # <-- Changed this
    @timer(interval=1)
    def ping(self):
        results = []
        for i in range(10):
            r = self.worker.sleep.call_async(i) # <-- Changed this
            results.append(r)
        # Wait for all results to finish
        results = [r.result() for r in results]
        logging.info(results)

class Worker:
    name = "worker"
    @rpc
    def sleep(self, number):
        import time
        time.sleep(0.5)
        return number
```
Sorry for opening an issue without doing enough research. I will close it.
