### ISSUE TITLE
Bug when using ClusterRpcClient

### ISSUE THREAD

**Issue by tyler46** [nameko/nameko#687]
**Describe the bug**
It seems that If I pass an **amqp uri**  different that ampq://guest:guest@localhost:5672, I get a `ConnectionRefusedError: [Errno 111] Connection refused`. The full traceback can be found bellow:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 138, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/cron/scheduler.py", line 71, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/cron/scheduler.py", line 67, in main
    process()
  File "/app/cron/scheduler.py", line 25, in process
    with ClusterRpcClient(uri=settings.AMQP_URI) as cluster_rpc:
  File "/usr/local/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 262, in __enter__
    return self.start()
  File "/usr/local/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 268, in start
    self.reply_listener.start()
  File "/usr/local/lib/python3.6/site-packages/nameko/standalone/rpc.py", line 94, in start
    ch = conn.channel()
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 289, in channel
    chan = self.transport.create_channel(self.connection)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 867, in connection
    max_retries=1, reraise_as_library_errors=False
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 445, in _ensure_connection
    callback, timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 874, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 809, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 149, in _connect
    "failed to resolve broker hostname"))
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**To Reproduce**
To reproduce it, you may follow the following steps:
1. Spawn a RabbitMQ instance that will run on a different port than the default, e.g. **5675**.

2. Define a simple nameko service that defines a rpc entrypoint.
```python
from nameko.rpc import rpc

class ServiceA:
     name = "service_a"
     @rpc
     def greet(self, value):
         return f"Hello {value}"
````

3. Define a another file that will make use of `ClusterRpcClient`.

```python
from nameko.standalone.rpc import ClusterRpcClient

with ClusterRpcClient(
    uri="amqp://guest:guest@0.0.0.0:5675"
) as cluster_rpc:
    v = cluster_rpc.service_a.greet("Nameko")
    print(v)
```

4. By running it you should see the error & corresponding traceback.

**Expected behavior**
I would expect that after making the rpc call, "Hello Nameko" would print.

**Environment (please complete the following information):**
 - Nameko version: v3.0.0-rc8
 - Python version: 3.6.9
 - OS: Debian Linux 

**Additional context**
After checking the relevant code `standalone/rpc.py` and trying to debug the amqp connection string, I have  found out that when instantiating ReplyListener at https://github.com/nameko/nameko/blob/v3.0.0-rc8/nameko/standalone/rpc.py#L212, no uri is provided, having as result to use the default one defined at https://github.com/nameko/nameko/blob/v3.0.0-rc8/nameko/constants.py#L27. I think we should include `uri` as argument, like:
` self.reply_listener = ReplyListener(queue, timeout=timeout, uri=self.amqp_uri)`

**Comment by asciifaceman** [comment]
In the process of troubleshooting my own issue https://github.com/nameko/nameko/issues/692 it seems `config.setup()` is still required.

```
    conf = {
        'AMQP_URI': "pyamqp://user:password@localhost"
    }
    config.setup(conf)
    
    with ClusterRpcProxy(conf) as rpc:
         ...
```
