### ISSUE TITLE
Nameko incompatible with dnspython 2.0.0

### ISSUE THREAD

**Issue by mattbennett** [nameko/nameko#688]
Raising a quick issue here to note https://github.com/eventlet/eventlet/issues/629

The currently released version of Eventlet is incompatible with the latest release of dnspython. Nameko depends on Eventlet which depends on dnspython.

DNS resolution fails, e.g.

```
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import socket
>>> socket.getaddrinfo("rabbitmq", 5672)
Traceback (most recent call last):
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 425, in resolve
    use_network=use_network)
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 380, in query
    return end()
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 359, in end
    raise result[1]
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "/appenv/lib/python3.7/site-packages/dns/resolver.py", line 1091, in query
    True)
  File "/appenv/lib/python3.7/site-packages/dns/resolver.py", line 1043, in resolve
    timeout = self._compute_timeout(start, lifetime)
  File "/appenv/lib/python3.7/site-packages/dns/resolver.py", line 950, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 5.118549108505249 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 490, in _getaddrinfo_lookup
    raise err
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "/appenv/lib/python3.7/site-packages/eventlet/support/greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
socket.gaierror: [Errno -3] Lookup timed out
```

A workaround is to pin `dnspython<2` in requirements files until a fix is released.

**Comment by eacmen** [comment]
Mayone one of the nameko maintainers knows one of the eventlet maintainers and can get this merged? https://github.com/eventlet/eventlet/pull/630
