### ISSUE TITLE
SSLContext RecursionError when requests made within service

### ISSUE THREAD

**Issue by asciifaceman** [nameko/nameko#693]
**Please use the [Discourse forum](https://discourse.nameko.io/) for support requests and questions.**

**Describe the bug**
With a simple service containing a request operation, an SSLContext recursion issue occurs.

Client:
```
>>> n.rpc.check_service.HTTPStatusOk("https://google.com")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/nameko/rpc.py", line 373, in __call__
  File "/Users/aasciifaceman/development/praetor/venv/lib/python3.7/site-packages/nameko/rpc.py", line 331, in result
    'heartbeat', config.get(HEARTBEAT_CONFIG_KEY, DEFAULT_HEARTBEAT)
nameko.exceptions.RemoteError: RecursionError maximum recursion depth exceeded
```

Service:
```
nameko run check --config nameko.yml
starting services: check_service
Connected to amqp://user:**@127.0.0.1:5672//
error handling worker <WorkerContext [check_service.HTTPStatusOk] at 0x10d90b2b0>: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/nameko/containers.py", line 388, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./check.py", line 18, in HTTPStatusOk
    r = requests.head(url,allow_redirects=True,verify=False)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connection.py", line 345, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 277, in create_urllib3_context
    context.options |= options
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 474 more times]
RecursionError: maximum recursion depth exceeded
```

**To Reproduce**
```
import urllib

import requests
from nameko.rpc import rpc


class CheckService:
    name = "check_service"

    @rpc
    def ping(self):
        return "pong"

    @rpc
    def HTTPStatusOk(self, url):
        """Checks that a stream URL is accessible"""
        r = requests.head(url,allow_redirects=True)
        return r.status_code

```

**Expected behavior**
```
>>> n.rpc.check_service.HTTPStatusOk("https://google.com")
200
```

**Environment (please complete the following information):**
 - Nameko version: 3.0.0rc8
 - Python version: 3.7.3
 - OS: Darwin Kernel Version 18.7.0 / 10.14.6 Mojave

**Additional context**
I am unable to reproduce outside of the nameko service container context.

```
20:48 $ python
Python 3.7.3 (default, Mar 27 2019, 09:23:32)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.head("https://google.com", allow_redirects=True)
>>> print(r.status_code)
200
```

Digging around I've seen some references to this issue on other projects in and around monkeypatching for eventlet, but usually the problem was NOT monkeypatching. I also found #411 which was closed as the issue owner downgraded python and it seemed to resolve - which may not be an option for me for compatibility.

**Comment by josewails** [comment]
I ran into the same issue today. I had to downgrade to requests==2.11.1 and not it works fine. Hope this helps @asciifaceman

**Comment by asciifaceman** [comment]
Unfortunately I don't seem to be so lucky @josewails :( 

```
Successfully installed requests-2.11.1
```

(yes, I uninstalled first)

```
Starting new HTTPS connection (1): google.com
error handling worker <WorkerContext [check_service.HTTPStatusOk] at 0x10451b0f0>: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/nameko/containers.py", line 388, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./check.py", line 18, in HTTPStatusOk
    r = requests.head(url,allow_redirects=True,verify=False)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 96, in head
    return request('head', url, **kwargs)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 291, in ssl_wrap_socket
    ciphers=ciphers)
  File "/Users/casciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 254, in create_urllib3_context
    context.options |= options
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 474 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by asciifaceman** [comment]
https://github.com/eventlet/eventlet/issues/371

I did find this, but unfortunately it doesn't appear the "fix" downgrade is compatible


`Successfully installed dnspython-1.16.0`

```
nameko run check --config nameko.yml
starting services: check_service
Connected to amqp://user:**@127.0.0.1:5672//
error handling worker <WorkerContext [check_service.HTTPStatusOk] at 0x108babba8>: wrap_socket() got an unexpected keyword argument '_context'
Traceback (most recent call last):
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/nameko/containers.py", line 388, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./check.py", line 18, in HTTPStatusOk
    r = requests.head(url,allow_redirects=True,verify=False)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/eventlet/green/ssl.py", line 437, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "/Users/asciifaceman/development/praetor/venv/lib/python3.7/site-packages/eventlet/green/ssl.py", line 76, in __new__
    *args, **kw
TypeError: wrap_socket() got an unexpected keyword argument '_context'
```

**Comment by asciifaceman** [comment]
I tried moving the request itself into a dependency provider but it seems it runs in the same context and there is no difference in result

```
import requests
from nameko.extensions import DependencyProvider


class NetRequestWrapper:
    '''
        Abstracting SSL requests because
    '''

    def get(self, url):
        x = requests.head(url, allow_redirects=True)
        return x.status_code
        

class NetRequest(DependencyProvider):

    def get_dependency(self, worker_ctx):
        return NetRequestWrapper()

```

```
nameko run check --config nameko.yml
starting services: check_service
Connected to amqp://user:**@127.0.0.1:5672//
Starting new HTTPS connection (1): bitdash-a.akamaihd.net
error handling worker <WorkerContext [check_service.HTTPStatusOk] at 0x10d0268d0>: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/Users/ccorbett/development/praetor/venv/lib/python3.7/site-packages/nameko/containers.py", line 388, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./check.py", line 23, in HTTPStatusOk
    r = self.rp.get(url)
  File "./netrequest.py", line 11, in get
    return requests.head(url, allow_redirects=True)
  File "/Users/ccorbett/development/praetor/venv/lib/python3.7/site-packages/requests/api.py", line 96, in head
    return request('head', url, **kwargs)
... brevity edit ...
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 507, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 473 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by asciifaceman** [comment]
This honestly seems to be a widespread issue with a half dozen resolutions for different people with different libraries and frameworks.

It just feels hopeless right now

**Comment by mattbennett** [comment]
I've just experienced this one for the first time, and the change that triggered it was to add a pytest plugin as a setup tools entrypoint. Even if the module is empty, the recursion error occurs.

**Comment by mattbennett** [comment]
The folks over at gevent have [an issue](https://github.com/gevent/gevent/issues/1016#issuecomment-328529454) that helped me find the problem here, I think.

The issue stems from modules being imported before the monkey patch is applied.

In the particular case above, the pytest plugin I installed was being imported before Nameko's own pytest plugin (which applies the monkey patch) and that early-importing plugin was importing requests -- hence requests was imported before the monkey patch was applied.

**Comment by asciifaceman** [comment]
> The folks over at gevent have [an issue](https://github.com/gevent/gevent/issues/1016#issuecomment-328529454) that helped me find the problem here, I think.
> 
> The issue stems from modules being imported before the monkey patch is applied.
> 
> In the particular case above, the pytest plugin I installed was being imported before Nameko's own pytest plugin (which applies the monkey patch) and that early-importing plugin was importing requests -- hence requests was imported before the monkey patch was applied.

I experience the issue with monkeypatching order being correct (no test plugin, no additional imports)

**Comment by mattbennett** [comment]
I've seen this multiple times now, and it's always because there's an import of requests before the monkey patch. It's easy to demonstrate this by adding a couple of print statements to the appropriate modules.

I cannot reproduce the error using your original example, even on the same Python and Nameko versions.

Can you post a repro where the issue happens and you've demonstrated that the monkeypatching order is correct?
