### ISSUE TITLE
2.13 fails to run with Precondition_Failure

### ISSUE THREAD

**Issue by Mendes11** [nameko/nameko#706]
**Please use the [Discourse forum](https://discourse.nameko.io/) for support requests and questions.**

**Describe the bug**
Nameko is failing to start due to Wrong Exchange configuration

**To Reproduce**
Updated from 2.12 to 2.13 with an already configured event exchange

**Environment (please complete the following information):**
 - Nameko version: 2.13
 - Python version: 3.6.9
 - OS: Debian

**Additional context**

Traceback: 

```
Traceback (most recent call last):
  File "/home/mendes/.virtualenvs/alert_domain/bin/nameko", line 8, in <module>
    sys.exit(main())
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/cli/main.py", line 119, in main
    args.main(args)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/cli/commands.py", line 110, in main
    main(args)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/cli/run.py", line 184, in main
    run(services, config, backdoor_port=args.backdoor_port)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/cli/run.py", line 131, in run
    service_runner.start()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/runners.py", line 66, in start
    SpawningProxy(self.containers).start()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/utils/concurrency/__init__.py", line 81, in spawning_method
    return list(pool.imap(call, self._items))
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenpool.py", line 252, in next
    val = self._next()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenpool.py", line 235, in _next
    return self.waiters.get().wait()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenthread.py", line 181, in wait
    return self._exit_event.wait()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/event.py", line 125, in wait
    result = hub.switch()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/utils/concurrency/__init__.py", line 76, in call
    return getattr(item, name)(*args, **kwargs)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/containers.py", line 189, in start
    self.extensions.all.setup()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/utils/concurrency/__init__.py", line 81, in spawning_method
    return list(pool.imap(call, self._items))
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenpool.py", line 252, in next
    val = self._next()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenpool.py", line 235, in _next
    return self.waiters.get().wait()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenthread.py", line 181, in wait
    return self._exit_event.wait()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/event.py", line 125, in wait
    result = hub.switch()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/utils/concurrency/__init__.py", line 76, in call
    return getattr(item, name)(*args, **kwargs)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/events.py", line 84, in setup
    super(EventDispatcher, self).setup()
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/nameko/messaging.py", line 164, in setup
    maybe_declare(entity, conn.channel())
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/kombu/common.py", line 121, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/kombu/common.py", line 161, in _maybe_declare
    entity.declare(channel=channel)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/kombu/entity.py", line 186, in declare
    nowait=nowait, passive=passive,
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/channel.py", line 614, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/connection.py", line 521, in on_inbound_method
    method_sig, payload, content,
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/mendes/.virtualenvs/alert_domain/lib/python3.6/site-packages/amqp/channel.py", line 280, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: Exchange.declare: (406) PRECONDITION_FAILED - inequivalent arg 'auto_delete' for exchange 'alert_domain.events' in vhost '/': received 'false' but current is 'true'

```

**Comment by Mendes11** [comment]
Looking at the changes, it appears that `auto_delete=True` configuration was removed in `get_event_exchange` function.

**Comment by stratosgear** [comment]
Hey, you are right!  This fails for me too, on 2.13.0.  Had to force back to 2.12.0, which is working.

I am on kombu 4.6.11, btw!

**Comment by iotknect** [comment]
I was able to solve it by deleting the exchange in rabbitmq. Nameko recreates it and everything works just fine. Queues were untouched so I didn't lose any message and everything was processed as soon as nameko service was restarted.

**Comment by tranvietanh1991** [comment]
I got the same issue, and figure out the latest changes of 2.13 on remove the `auto_delete=True` was causing it. I've made a  [PR#711](https://github.com/nameko/nameko/pull/711) to revert that changes since that feature is now un-deprecated.
